name: Deploy React Vite Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/react-upload-file --build-arg VITE_API_BASE_URL="${{ secrets.VITE_API_BASE_URL }}" .

      - name: Publish image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/react-upload-file:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/react-upload-file:latest

      - name: Stop and remove existing container
        run: |
          docker stop aws-reactjs-app-container || true
          docker rm aws-reactjs-app-container || true

      - name: Run Docker container
        run: |
          docker run -d -p 3006:3006 --name aws-reactjs-app-container \
            -e VITE_API_BASE_URL="${{ secrets.VITE_API_BASE_URL }}" \
            ${{ secrets.DOCKER_USERNAME }}/react-upload-file:latest

      - name: Verify container status
        run: docker ps -a | grep aws-reactjs-app-container
